package net.thevpc.nsh.cmd.impl.common;

import net.thevpc.nsh.cmd.NshBuiltinDefault;
import net.thevpc.nsh.eval.NshExecutionContext;
import net.thevpc.nuts.*;
import net.thevpc.nuts.cmdline.NArg;
import net.thevpc.nuts.cmdline.NCmdLine;
import net.thevpc.nuts.io.NPath;
import net.thevpc.nuts.io.NPathPermission;
import net.thevpc.nuts.platform.NEnv;
import net.thevpc.nuts.platform.NShellFamily;
import net.thevpc.nuts.spi.NComponentScope;
import net.thevpc.nuts.spi.NScopeType;
import net.thevpc.nuts.text.NMsg;
import net.thevpc.nuts.util.*;

import java.util.*;

@NComponentScope(NScopeType.WORKSPACE)
@NScore(fixed = NScorable.DEFAULT_SCORE)
public class MakeWrapperCommand extends NshBuiltinDefault {

    public MakeWrapperCommand() {
        super("make-wrapper", Options.class);
    }

    @Override
    protected boolean nextOption(NArg arg, NCmdLine cmdLine, NshExecutionContext context) {
        Options options = context.getOptions();
        NArg a;

        if ((a = cmdLine.nextEntry("--target").orNull()) != null) {
            options.target = a.getStringValue().orNull();
            return true;
        }
        if ((a = cmdLine.nextEntry("--default").orNull()) != null) {
            options.defaultExec = a.getStringValue().orNull();
            return true;
        }
        if ((a = cmdLine.nextFlag("--cmd").orNull()) != null) {
            String value = a.getStringValue().orNull();
            if (value == null) {
                cmdLine.throwError(NMsg.ofC("--cmd requires a value (either <path> or <name>=<path>)"));
                return false;
            }
            options.cmds.add(value);
            return true;
        }
        return false;
    }

    @Override
    protected void main(NCmdLine cmdLine, NshExecutionContext context) {
        Options options = context.getOptions();
        if (NBlankable.isBlank(options.target)) {
            cmdLine.throwError(NMsg.ofC("--target is required"));
            return;
        }

        NPath targetPath = NPath.of(options.target).toAbsolute(context.getDirectory());
        Map<String, String> subcommands = new LinkedHashMap<>();

        for (String cmdSpec : options.cmds) {
            String name, execPath;
            int eq = cmdSpec.indexOf('=');
            if (eq >= 0) {
                name = cmdSpec.substring(0, eq);
                execPath = cmdSpec.substring(eq + 1);
                if (name.isEmpty()) {
                    cmdLine.throwError(NMsg.ofC("invalid --cmd: empty name in '%s'", cmdSpec));
                    return;
                }
            } else {
                NPath path = NPath.of(cmdSpec);
                name = path.name();
                execPath = cmdSpec;
            }
            NPath resolved = NPath.of(execPath).toAbsolute(context.getDirectory());
            subcommands.put(name, resolved.toString());
        }

        // Determine platform
        NEnv env = NEnv.of();
        switch (env.osFamily()) {
            case WINDOWS: {
                if(NEnv.of().shellFamily()== NShellFamily.WIN_POWER_SHELL){
                    // Optionally generate PowerShell script as well
                    generatePowerShellScript(targetPath, subcommands, options.defaultExec, context);
                }else {
                    generateBatchScript(targetPath, subcommands, options.defaultExec, context);
                }
                break;
            }
            default: // LINUX, MACOS, etc.
                generateUnixScript(targetPath, subcommands, options.defaultExec, context);
                break;
        }
    }

    private void generateUnixScript(NPath targetPath, Map<String, String> subcommands, String defaultExec, NshExecutionContext context) {
        NStringBuilder script = NStringBuilder.of();
        script.println("#!/usr/bin/env bash");
        script.println("# Auto-generated by make-wrapper");
        script.println("WRAPPER_NAME=\"$(basename \"$0\")\"");
        script.println();
        script.println("if [ \"$WRAPPER_NAME\" = \"" + targetPath.name() + "\" ]; then");
        script.println("    if [ $# -eq 0 ]; then");
        if (defaultExec != null) {
            script.println("        exec \"" + NPath.of(defaultExec).toAbsolute(context.getDirectory()) + "\" \"$@\"");
        } else {
            script.println("        echo \"No subcommand specified and no default command defined.\" >&2");
            script.println("        echo \"Usage: $0 <subcommand> [args...]\" >&2");
            script.println("        exit 1");
        }
        script.println("    else");
        script.println("        CMD=\"$1\"; shift");
        script.println("        case \"$CMD\" in");
        for (Map.Entry<String, String> e : subcommands.entrySet()) {
            script.println("            " + e.getKey() + ") exec \"" + e.getValue() + "\" \"$@\" ;;");
        }
        script.println("            *) echo \"Unknown subcommand: $CMD\" >&2; exit 1 ;;");
        script.println("        esac");
        script.println("    fi");
        script.println("else");
        script.println("    case \"$WRAPPER_NAME\" in");
        for (Map.Entry<String, String> e : subcommands.entrySet()) {
            script.println("        " + e.getKey() + ") exec \"" + e.getValue() + "\" \"$@\" ;;");
        }
        script.println("        *) echo \"Unknown subcommand: $WRAPPER_NAME\" >&2; exit 1 ;;");
        script.println("    esac");
        script.println("fi");

        targetPath.writeString(script.toString());
        targetPath.addPermissions(NPathPermission.CAN_EXECUTE);
        context.out().println(NMsg.ofC("Created Unix wrapper: %s", targetPath));
    }

    private void generateBatchScript(NPath targetPath, Map<String, String> subcommands, String defaultExec, NshExecutionContext context) {
        // Change extension to .bat if target ends with no extension or .sh
        NPath batPath = targetPath;
        if (!batPath.toString().toLowerCase().endsWith(".bat")) {
            batPath = NPath.of(batPath.toString() + ".bat");
        }
        NStringBuilder script = NStringBuilder.of();
        script.println("@echo off");
        script.println("REM Auto-generated by make-wrapper");
        script.println("set WRAPPER_NAME=%~n0");
        script.println();
        script.println("if \"%WRAPPER_NAME%\"==\"" + batPath.name().replace(".bat", "") + "\" (");
        script.println("    if \"%*\"==\"\" (");
        if (defaultExec != null) {
            script.println("        \"" + NPath.of(defaultExec).toAbsolute(context.getDirectory()) + "\" %*");
        } else {
            script.println("        echo No subcommand specified and no default command defined.");
            script.println("        echo Usage: %0 ^<subcommand^> [args...]");
            script.println("        exit /b 1");
        }
        script.println("    ) else (");
        script.println("        set CMD=%1");
        script.println("        shift");
        script.println("        goto dispatch_%CMD% 2>nul");
        script.println("        echo Unknown subcommand: %CMD%");
        script.println("        exit /b 1");
        script.println("    )");
        script.println(") else (");
        script.println("    set CMD=%WRAPPER_NAME%");
        script.println("    goto dispatch_%CMD% 2>nul");
        script.println("    echo Unknown subcommand: %CMD%");
        script.println("    exit /b 1");
        script.println(")");
        script.println();
        for (Map.Entry<String, String> e : subcommands.entrySet()) {
            script.println(":dispatch_" + e.getKey());
            script.println("\"" + e.getValue() + "\" %*");
            script.println("exit /b %errorlevel%");
        }

        batPath.writeString(script.toString());
        // No executable flag on Windows
        context.out().println(NMsg.ofC("Created Batch wrapper: %s", batPath));
    }

    private void generatePowerShellScript(NPath targetPath, Map<String, String> subcommands, String defaultExec, NshExecutionContext context) {
        NPath psPath = NPath.of(targetPath.toString() + ".ps1");
        NStringBuilder script = NStringBuilder.of();
        script.println("# Auto-generated by make-wrapper");
        script.println("$WRAPPER_NAME = (Get-Item $MyInvocation.MyCommand.Path).BaseName");
        script.println();
        script.println("if ($WRAPPER_NAME -eq \"" + targetPath.name() + "\") {");
        script.println("    if ($args.Count -eq 0) {");
        if (defaultExec != null) {
            script.println("        & \"" + NPath.of(defaultExec).toAbsolute(context.getDirectory()) + "\" @args");
        } else {
            script.println("        Write-Host \"No subcommand specified and no default command defined.\"");
            script.println("        Write-Host \"Usage: $($MyInvocation.MyCommand.Name) <subcommand> [args...]\"");
            script.println("        exit 1");
        }
        script.println("    } else {");
        script.println("        $CMD = $args[0]");
        script.println("        $script:args = $args[1..$args.Count]");
        script.println("        switch ($CMD) {");
        for (Map.Entry<String, String> e : subcommands.entrySet()) {
            script.println("            \"" + e.getKey() + "\" { & \"" + e.getValue() + "\" @args; break }");
        }
        script.println("            default { Write-Host \"Unknown subcommand: $CMD\"; exit 1 }");
        script.println("        }");
        script.println("    }");
        script.println("} else {");
        script.println("    switch ($WRAPPER_NAME) {");
        for (Map.Entry<String, String> e : subcommands.entrySet()) {
            script.println("        \"" + e.getKey() + "\" { & \"" + e.getValue() + "\" @args; break }");
        }
        script.println("        default { Write-Host \"Unknown subcommand: $WRAPPER_NAME\"; exit 1 }");
        script.println("    }");
        script.println("}");

        psPath.writeString(script.toString());
        context.out().println(NMsg.ofC("Created PowerShell wrapper: %s", psPath));
    }

    @Override
    protected boolean nextNonOption(NArg arg, NCmdLine cmdLine, NshExecutionContext context) {
        cmdLine.throwError(NMsg.ofC("unexpected argument: %s", arg.image()));
        return false;
    }

    public static class Options {
        String target;
        String defaultExec;
        List<String> cmds = new ArrayList<>();
    }
}