package net.thevpc.nsh.cmd.impl.common;

import net.thevpc.nsh.cmd.NshBuiltinDefault;
import net.thevpc.nsh.eval.NshExecutionContext;
import net.thevpc.nuts.*;
import net.thevpc.nuts.cmdline.NArg;
import net.thevpc.nuts.cmdline.NCmdLine;
import net.thevpc.nuts.core.NWorkspace;
import net.thevpc.nuts.io.NPath;
import net.thevpc.nuts.io.NPathPermission;
import net.thevpc.nuts.platform.NEnv;
import net.thevpc.nuts.platform.NOsFamily;
import net.thevpc.nuts.spi.NComponentScope;
import net.thevpc.nuts.spi.NScopeType;
import net.thevpc.nuts.text.NMsg;
import net.thevpc.nuts.util.*;

import java.util.LinkedHashMap;
import java.util.Map;

@NComponentScope(NScopeType.WORKSPACE)
@NScore(fixed = NScorable.DEFAULT_SCORE)
public class MakeWrapperCommand extends NshBuiltinDefault {

    public MakeWrapperCommand() {
        super("make-wrapper", Options.class);
    }

    @Override
    protected boolean nextOption(NArg arg, NCmdLine cmdLine, NshExecutionContext context) {
        Options options = context.getOptions();
        NArg a;

        if ((a = cmdLine.nextEntry("--target").orNull()) != null) {
            options.target = a.getStringValue().orNull();
            return true;
        }
        if ((a = cmdLine.nextEntry("--default").orNull()) != null) {
            String value = a.getStringValue().orNull();
            if (NBlankable.isBlank(value)) {
                cmdLine.throwError(NMsg.ofC("--default requires format name=path"));
                return false;
            }
//            if (value == null || !value.contains("=")) {
//                cmdLine.throwError(NMsg.ofC("--default requires format name=path"));
//                return false;
//            }
            options.defaultSpec = new NameAndPath(value);
            return true;
        }
        if ((a = cmdLine.nextEntry("--cmd").orNull()) != null) {
            String value = a.getStringValue().orNull();
            if (NBlankable.isBlank(value)) {
                cmdLine.throwError(NMsg.ofC("--cmd requires format name=path"));
                return false;
            }
            options.cmdSpecs.add(new NameAndPath(value));
            return true;
        }
        return false;
    }

    @Override
    protected void main(NCmdLine cmdLine, NshExecutionContext context) {
        Options options = context.getOptions();
        if (NBlankable.isBlank(options.target)) {
            cmdLine.throwError(NMsg.ofC("--target is required"));
            return;
        }
        if (options.defaultSpec == null) {
            cmdLine.throwError(NMsg.ofC("--default is required"));
            return;
        }

        Map<String, String> commands = new LinkedHashMap<>();
        // parse default
        NPath pp = options.defaultSpec.path.toAbsolute(context.getDirectory());
        pp.addPermissions(NPathPermission.CAN_EXECUTE);
        commands.put(options.defaultSpec.name, pp.toString());

        // parse extra cmds
        for (NameAndPath spec : options.cmdSpecs) {
            if (commands.containsKey(spec.name)) {
                cmdLine.throwError(NMsg.ofC("duplicate command name: %s", spec.name));
                return;
            }
            pp = spec.path.toAbsolute(context.getDirectory());
            pp.addPermissions(NPathPermission.CAN_EXECUTE);
            commands.put(spec.name, pp.toString());
        }

        NPath targetPath = NPath.of(options.target).toAbsolute(context.getDirectory());
        NEnv env = NEnv.of();
        if (env.osFamily() == NOsFamily.WINDOWS) {
            generateBatchScript(targetPath, commands, options.defaultSpec.name, context);
        } else {
            generateUnixScript(targetPath, commands, options.defaultSpec.name, context);
        }
    }

    private void generateUnixScript(NPath targetPath, Map<String, String> commands, String defaultCmd, NshExecutionContext context) {
        NStringBuilder sb = NStringBuilder.of();
        sb.println("#!/usr/bin/env bash");
        sb.println("# Auto-generated by make-wrapper");
        sb.println();
        sb.println("DEFAULT_CMD=\"" + defaultCmd + "\"");
        sb.println("DEFAULT_PATH=\"" + commands.get(defaultCmd) + "\"");
        for (Map.Entry<String, String> e : commands.entrySet()) {
            sb.println(e.getKey().toUpperCase() + "_PATH=\"" + e.getValue() + "\"");
        }
        sb.println();
        sb.println("# Show help if requested");
        sb.println("if [ \"$1\" = \"--help\" ] || [ \"$1\" = \"-h\" ]; then");
        sb.println("    echo \"Usage: $(basename \"$0\") [<command>] [args...]\"");
        sb.println("    echo \"Commands:\"");
        for (String name : commands.keySet()) {
            sb.println("    echo \"  " + name + "\"");
        }
        sb.println("    echo \"If no command is given, the default command '$defaultCmd' is used.\"");
        sb.println("    exit 0");
        sb.println("fi");
        sb.println();
        sb.println("if [ \"$1\" = \"--version\" ]; then");
        sb.println("    echo \"$(basename \"$0\") version " + NWorkspace.of().runtimeId().version() + "\"");
        sb.println("    exit 0");
        sb.println("fi");
        sb.println();
        sb.println("if [ $# -eq 0 ]; then");
        sb.println("    exec \"$DEFAULT_PATH\"");
        sb.println("else");
        sb.println("    CMD=\"$1\"; shift");
        sb.println("    case \"$CMD\" in");
        for (Map.Entry<String, String> e : commands.entrySet()) {
            sb.println("        " + e.getKey() + ") exec \"" + e.getValue() + "\" \"$@\" ;;");
        }
        sb.println("        *)      exec \"$DEFAULT_PATH\" \"$CMD\" \"$@\" ;;");
        sb.println("    esac");
        sb.println("fi");

        targetPath.writeString(sb.toString());
        targetPath.addPermissions(NPathPermission.CAN_EXECUTE);
        context.out().println(NMsg.ofC("Created Unix wrapper: %s", targetPath));
    }

    private void generateBatchScript(NPath targetPath, Map<String, String> commands, String defaultCmd, NshExecutionContext context) {
        NPath batPath = targetPath;
        if (!batPath.toString().toLowerCase().endsWith(".bat")) {
            batPath = NPath.of(batPath + ".bat");
        }
        String defaultPath = commands.get(defaultCmd);
        NStringBuilder sb = NStringBuilder.of();
        sb.println("@echo off");
        sb.println("REM Auto-generated by make-wrapper");
        sb.println("setlocal enabledelayedexpansion");
        sb.println("set DEFAULT_CMD=" + defaultCmd);
        sb.println("set DEFAULT_PATH=" + defaultPath);
        for (Map.Entry<String, String> e : commands.entrySet()) {
            sb.println("set " + e.getKey().toUpperCase() + "_PATH=" + e.getValue());
        }
        sb.println();
        sb.println("if \"%1\"==\"--help\" goto :help");
        sb.println("if \"%1\"==\"-h\" goto :help");
        sb.println("if \"%1\"==\"--version\" goto :version");
        sb.println();
        sb.println("if \"%*\"==\"\" goto :run_default");
        sb.println("set CMD=%1");
        sb.println("shift");
        sb.println("for %%A in (" + String.join(" ", commands.keySet()) + ") do (");
        sb.println("    if /i \"!CMD!\"==\"%%A\" goto :dispatch_%%A");
        sb.println(")");
        sb.println("rem fallback to default with first argument as part of args");
        sb.println("\"%DEFAULT_PATH%\" %CMD% %*");
        sb.println("exit /b %errorlevel%");
        sb.println();
        sb.println(":run_default");
        sb.println("\"%DEFAULT_PATH%\" %*");
        sb.println("exit /b %errorlevel%");
        sb.println();
        sb.println(":help");
        sb.println("echo Usage: %~n0 [command] [args...]");
        sb.println("echo Commands:");
        for (String name : commands.keySet()) {
            sb.println("echo   " + name);
        }
        sb.println("echo If no command is given, the default command '" + defaultCmd + "' is used.");
        sb.println("exit /b 0");
        sb.println();
        sb.println(":version");
        sb.println("echo %~n0 version " + NWorkspace.of().runtimeId().version());
        sb.println("exit /b 0");
        sb.println();
        for (Map.Entry<String, String> e : commands.entrySet()) {
            sb.println(":dispatch_" + e.getKey());
            sb.println("\"" + e.getValue() + "\" %*");
            sb.println("exit /b %errorlevel%");
        }

        batPath.writeString(sb.toString());
        // no executable flag needed on Windows
        context.out().println(NMsg.ofC("Created Batch wrapper: %s", batPath));
    }

    @Override
    protected boolean nextNonOption(NArg arg, NCmdLine cmdLine, NshExecutionContext context) {
        cmdLine.throwError(NMsg.ofC("unexpected argument: %s", arg.image()));
        return false;
    }

    public static class NameAndPath {
        String name;
        NPath path;

        public NameAndPath(String name, NPath path) {
            this.name = name;
            this.path = path;
        }

        public NameAndPath(String nameAndPath) {
            int i = nameAndPath.indexOf('=');
            if (i >= 0) {
                this.name = nameAndPath.substring(0, i);
                this.path = NPath.of(nameAndPath.substring(i + 1));
            }else{
                this.path = NPath.of(nameAndPath);
                this.name = path.name();
                if(NBlankable.isBlank(name)){
                    throw new NIllegalArgumentException(NMsg.ofC("invalid cmd name"));
                }
            }
        }

    }

    public static class Options {
        String target;
        NameAndPath defaultSpec;
        java.util.List<NameAndPath> cmdSpecs = new java.util.ArrayList<>();
    }
}